name: Contact The Project
description: Contact the project directly.
title: "[Contact] Re: "
labels: ["Communication Required"]
assignees:
  - spydmobile
  - nealmcloughlin
  - BadgerOnABike

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out to us! We are still just volunteers, so this message will go into a queue and someone from the team will read it and respond accordingly.
  - type: textarea
    id: details
    attributes:
      label: Message Body
      description: A detailed message to send us.
      placeholder: Write your message here!
    validations:
      required: true
