name: REDapp Feature Request
description: Request a new feature in REDapp
title: "[REDapp FR]: "
labels: ["feature", "triage", "REDapp"]
assignees:
  - spydmobile
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! By submitting this issue, you agree to follow our [Code of Conduct](https://firegrowthmodel.ca/pages/conduct.html)
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-is-needed
    attributes:
      label: What is needed?
      description: Also tell us, how you might imagine this is implemented!
      placeholder: Tell us what you want!
      value: "I would like a purple widget added to the about screen below the version number!"
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: How will this improve the project or tool?
      description: Proivide additional context.
  - type: checkboxes
    id: approval
    attributes:
      label: Approvals Process
      description: All to be completed for induction into the tool
      options:
        - label: Testing For Issue
        - label: Executive Approval
        - label: Merge
        - label: Provide Attribution
