name: REDapp Support Request
description: Request a new feature in REDapp
title: "[REDapp help]: "
labels: ["support", "triage", "REDapp"]
assignees:
  - emdiaz0031
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this supportrequest ! 
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happend
    attributes:
      label: What happend?
      description: Also tell us, what you may have already tried to do!
      placeholder: Tell us what did!
      value: "I pushed the go button but nothing happend, I tried restarting but it still did not go!"
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: what did you expect/was supposed to happen?
      description: Proivide additional context.

