name: REDapp Project Task
description: Creates a task for the REDapp Team
title: "[REDapp TASK]: "
labels: ["task", "triage"]
assignees:
  - spydmobile
body:
  - type: markdown
    attributes:
      value: |
        Please complete the following project task:
  - type: textarea
    id: details
    attributes:
      label: Explain the task in detail
      description: we ask you to use checkist items for multiple concenrs.