name: REDapp Project Task
description: Creates a task for the REDapp Team
title: "[REDapp TASK]: "
labels: ["task", "triage", "REDapp"]
assignees:
  - spydmobile
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! By submitting this issue, you agree to follow our [Code of Conduct](https://firegrowthmodel.ca/pages/conduct.html)
